language: clojure
sudo: no
before_install:
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install emacs-25.2-travis --skip --use
  - export EMACS="$HOME/.evm/bin/emacs"
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask
lein: lein
env:
 - PROFILE=default
 - PROFILE=1.8
 - PROFILE=1.8-direct
script:
 - lein with-profiles $PROFILE test
 - make travis
jdk:
 - oraclejdk8
notifications:
   email:
     - travis@russet.org.uk
